### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by ababaian** [ababaian/serratus#5]
### AWS Specific Tasks
- [x]  `sratoolkit` works natively with AWS/GCP to access `SRA` archive files. Most data is stored in this format and requires `fastq-dump` from `sratoolkit` to start the pipeline. Some modern SRA entries already contain bam or fastq files, these would be faster to access via `fusera`. Add a "Try Fusera" to access fq files first then fall-back on sratoolkit fq dump which is the current default
- [x] Try to abstract away the entire `serratus-align` layer into AWS Lambda functions. See: [1](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-walkthrough.html) [2](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html).
- [x] ~Do a price comparison for `serratus-dl` between using C5.large and  i3.large instances, the latter have 2 CPU, high ram and 400 GB internal storage as part of the machine. You need to mount the internal volume yourself~ Issue #6 
- [x] ~From `SraRunInfo` table we know the size of the file in Mb. Can we dynamically/rapidly provision how much EBS space the EC2 instance has so that it's say 5 Gb + 3xSRA size. i.e. for a 2 Gb SRA it will have 5 Gb + 3x2 = 11 Gb. Then the next job is 100 Gb so we'll need 5 Gb + 3x100 = 305 Gb on EBS, then the next job is 200 Mb and we need ...~ Issue #4 

### BASH /Linux tasks
- [x] Build `bowtie2` on ARM, to take advantage of ~1/2 price A1 instances. Also `samtools` and `blastn`.

### Docker tasks
- [x] Research available `BLAST` containers and time the efficiency of each implementation.

### Bioinformatics tasks
- [x] Find software implementations of `Bloom Filters` that we can use to stream data through and select possible CoV Reads
- [x] Create an annotated list of SRA libraries with known Coronaviruses in the samples (i.e. SARS cell culture, SARS-CoV-2 accessions).
- [x] Create a simulated test-data set, using a baseline human transcriptome (cell line?) 'spike in' simulated viral genome/transcripts at different quantities so we can test the sensitivity/specificity of our pipeline versus a known standard.

**Comment by mathemage** [comment]
@jefftaylor42 and @ababaian if you actually tick/check the checkboxes in the list, you should see how many tasks have been finished/moved to a separate issue:

E.g. The #8 in https://github.com/ababaian/serratus/issues shows `0 of 3` next to the TODO list emoji ;-)

**Comment by mathemage** [comment]
@jefftaylor42 BASH /Linux tasks -> #8 (you can ~~strikethrough~~ and reference the issue)

**Comment by mathemage** [comment]
@jefftaylor42 
**AWS Specific Tasks**, 1st task -> #12 (you can ~~strikethrough~~ and reference the issue)

**Comment by mathemage** [comment]
@jefftaylor42 
**AWS Specific Tasks**, 2nd task -> #13 (you can ~~strikethrough~~ and reference the issue)

**Comment by mathemage** [comment]
@jefftaylor42 
**Docker tasks** -> #14 (you can ~~strikethrough~~ and reference the issue)

**Comment by mathemage** [comment]
@jefftaylor42 
**Bioinformatics tasks**, 1st task -> #15 (you can ~~strikethrough~~ and reference the issue)

**Comment by mathemage** [comment]
@jefftaylor42 
**Bioinformatics tasks**, 2nd task -> #16 (you can ~~strikethrough~~ and reference the issue)

**Comment by mathemage** [comment]
@jefftaylor42 
**Bioinformatics tasks**, 3rd task -> #17 (you can ~~strikethrough~~ and reference the issue)

**Comment by mathemage** [comment]
@jefftaylor42 @ababaian 
I've migrated all TODOs from here to https://github.com/ababaian/serratus/issues
You can (tick all TODO boxes) and close this issue (it shouldn't disappear/be deleted, it would just be archived on Github repo).

**Comment by ababaian** [comment]
Nice :+1:  I think the project TODO will be much better. Thank you!

**Comment by mathemage** [comment]
@ababaian Also don't forget to add all the new issues to your project [TODO list](https://github.com/ababaian/serratus/projects/1) so that you guys can have the dashboard with the 3-columns.
